### ISSUE TITLE
RfC / DevCon 2015: Refactor template engine

### ISSUE THREAD

**Issue by sidler** [kajona/kajonacms#71]
the current template engine is based on a single class and provides a rather complex workflow. templates (and sections) are read and identified by a key, the key has to be used to fill / process the template afterwards.
This should be moved to an internal process, the whole internal logic should be refactored and validated.

**Comment by k42b3** [comment]
Some additional thoughts regarding the template engine. So the template engine is currently
a toolkit which provides html chunks for specific cases i.e. a formentry, data table, etc.
In most cases we have to write some html which "glues" these html chunks together. Since we dont
want to write any html inside the controller, it would be cool to have an template engine like
this:
 
    public function actionList()
    {
        $news = // get data from the orm
     
        return $templateEnging->render('some/where/template.html', array(
            'news' => $news
        ));
    }
 
We can set a template file which is loaded and pass the data which we collected in the controller.
This would seperate more the logic from the presentation. As template engine we could think about
using an engine like twig which has a great syntax and provides if, for, statments etc. This is
currently not possible in the elements.tpl there we can replace only keys with specific values.
Probably it would be great to integrate the toolkit elements also in the template engine.

**Comment by sidler** [comment]
what you're describing is exactly the way we're currently handling the portal template stuff. the backend is structured differently to remain a unified appereance

**Comment by sidler** [comment]
some first implementations are tracked within the branch "templatecontainer": https://github.com/kajona/kajonacms/tree/features/templatecontainer
